export const CHANGE_LIST = 'home/CHANGE_LIST';
export const CHANGE_RECOMMEND_LIST = 'home/CHANGE_RECOMMEND_LIST';
export const HANDLE_MOUSE_ENTER = 'home/HANDLE_MOUSE_ENTER';
export const HANDLE_MOUSE_LEAVE = 'home/HANDLE_MOUSE_LEAVE';