export const CHANGE_TOPIC_LIST = 'home/CHANGE_TOPIC_LIST';
export const CHANGE_LIST = 'home/CHANGE_LIST';
export const CHANGE_RECOMMEND_LIST = 'home/CHANGE_RECOMMEND_LIST';
export const CHANGE_AUTHOR_LIST = 'home/CHANGE_AUTHOR_LIST';
export const HANDLE_MOUSE_ENTER = 'home/HANDLE_MOUSE_ENTER';
export const HANDLE_MOUSE_LEAVE = 'home/HANDLE_MOUSE_LEAVE';
export const CHANGE_PAGE = 'home/CHANGE_PAGE';